version: 2
jobs:
  build:
    working_directory: ~/node-aws
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t madecomfyau/node-aws .
      - run:
          name: Login to Dockerhub
          command: |
            docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag madecomfyau/node-aws madecomfyau/node-aws:8
              docker push madecomfyau/node-aws
            fi
